# Site
repository: klce/klce.github.io
favicon: images/favicon.ico

# Personal info
name: Kevin Esguerra
title: Software Engineer
email: klcesguerra@gmail.com
website: www.github.com/klce/klce.github.io

# Social links
github_username:  klce
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: in/kevin-esguerra-359b8253
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Lorem ipsum

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Lorem ipsum

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
